#!/usr/bin/env bash

export PATH="$HOME/.local/bin:$HOME/.asdf/bin:$HOME/.asdf/shims:$PATH"

# macos default path
# export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin" || source /etc/profile

# ubuntu default path
# export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

# case statement to choose input arguments
case "$1" in
  	install)
		# Build the environment
		sh -c "make install"
		;;
    run)
        # Run the playbook
        ansible-playbook \
            -i ./ansible/hosts \
            ./ansible/playbook.yml
        ;;
    run-dev)
        # Run the playbook with tags and debug
        ansible-playbook \
            -i ./ansible/hosts \
            ./ansible/playbook.yml \
            --tags test,qa -vvv
        ;;
    install-precommit)
        # Install pre-commit hooks
        pre-commit install
        ;;
    update-precommit)
        # Update pre-commit hooks
        pre-commit autoupdate
        ;;
  	release)
		# Build and publish the app
		sh -c "make release"
		;;
    test)
        # Run tests
        sh -c "make test"
        ;;
  	*)
		echo $"Usage: $0 {install|release|test}"
		exit 1
esac
