version: "3"

services:
  app:
    container_name: mvp-app
    hostname: mvp
    platform: linux/amd64             # linux/amd64 / linux/arm64/v8
    tty: true                         # false for `entrypoint` in Dockerfile
    stdin_open: true                  # false for `entrypoint` in Dockerfile
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - DEBIAN_FRONTEND=noninteractive
    ports:
      - "8000:8000/tcp"
      - "8080:8080/tcp"
    volumes:
      - ./:/app
    working_dir: /app
