apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp
  labels:
    app: mvp
spec:
  selector:
    matchLabels:
      app: mvp
  template:
    metadata:
      labels:
        app: mvp
    spec:
      containers:
        - name: mvp
          image: mvp:latest
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 8000
