# https://github.com/devcontainers/ci/blob/main/docs/github-action.md

name: 'devcontainer'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
  schedule: # rebuild once a week at midnight on saturday
    - cron: '0 0 * * 6'

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64, arm64]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image and run command in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/pythoninthegrass/mvp
          cacheFrom: ghcr.io/pythoninthegrass/mvp
          noCache: false
          push: always
          runCmd: |
            make help
