name: Run pytest

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.py'
  pull_request:
    branches:
      - main
      - master
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.x'

    - name: Cache apt packages
      uses: actions/cache@v4
      env:
        cache-name: cache-apt
      with:
        path: /var/lib/apt/lists
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.github/workflows/packages.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Cache pip packages
      uses: actions/cache@v4
      env:
        cache-name: cache-pip
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Install system dependencies
      run: |
        if [ -s .github/workflows/packages.txt ]; then
          sudo apt-get update
          sudo xargs -a .github/workflows/packages.txt apt-get install -y
        fi

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip pytest
        python -m pip install -r requirements.txt

    - name: Run pytest
      run: pytest -s
